# HackerRank ProjectEuler+ Problem 29: Distinct Powers
# https://www.hackerrank.com/contests/projecteuler/challenges/euler029/problem
#
# Project Euler: https://projecteuler.net/problem=29
# Solution: https://aliramadhan.me/blog/project-euler/problem-0029/
#
# Problem Statement:
#   Consider all integer combinations of a^b for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
#
#   2^2 = 4,  2^3 = 8,   2^4 = 16,  2^5 = 32
#   3^2 = 9,  3^3 = 27,  3^4 = 81,  3^5 = 243
#   4^2 = 16, 4^3 = 64,  4^4 = 256, 4^5 = 1024
#   5^2 = 25, 5^3 = 125, 5^4 = 625, 5^5 = 3125
#
#   If they are then placed in numerical order, with any repeats removed, we get
#   the following sequence of 15 distinct terms:
#   4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125.
#
#   How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ N
#   and 2 ≤ b ≤ N?
#
# Input Format:
#   Input contains an integer N.
#
# Constraints:
#   2 ≤ N ≤ 10^5
#
# Output Format:
#   Print the answer corresponding to the test case.
#
# Sample Input:
#   5
#
# Sample Output:
#   15

function count_distinct_powers(a_min, a_max, b_min, b_max; similarity_threshold=1e-10)
    powers = Float64[]
    sizehint!(powers, (a_max - a_min + 1) * (b_max - b_min + 1))

    for a in a_min:a_max
        loga = log(a)
        for b in b_min:b_max
            push!(powers, b * loga)
        end
    end

    sort!(powers)

    count = 1
    for i in 2:length(powers)
        if powers[i] - powers[i-1] > similarity_threshold
            count += 1
        end
    end

    return count
end

N = parse(Int, readline())
println(count_distinct_powers(2, N, 2, N))
