"""
Project Euler Problem 44: Pentagon Numbers

Pentagonal numbers are generated by the formula, P_n=n(3n-1)/2. The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8.
However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, P_j and P_k, for which their sum and difference are pentagonal
and D = |P_k - P_j| is minimised; what is the value of D?
"""
module Problem044

"""
    pentagonal(n)

Compute the nth pentagonal number using the formula P_n = n(3n-1)/2.
"""
function pentagonal(n)
    return (n * (3n - 1)) ÷ 2
end

"""
    is_pentagonal(p)

Check if a number p is a pentagonal number by determining if (1 + sqrt(1 + 24p))/6 is a positive integer.
This uses the inverse of the pentagonal formula to efficiently check without generating all pentagonal numbers.
"""
function is_pentagonal(p)
    if p <= 0
        return false
    end

    discriminant = 1 + 24 * p
    r = isqrt(discriminant)
    if r^2 != discriminant
        return false
    end

    if (1 + r) % 6 != 0
        return false
    end

    return true
end

"""
    find_minimum_d()

Find the value of D = |P_k - P_j| where P_j and P_k are pentagonal numbers
whose sum and difference are also pentagonal, and D is minimized.

Uses an efficient search strategy by:
1. Checking pairs in order of increasing difference
2. Early-skipping pairs that can't have a smaller difference than already found
"""
function find_minimum_d()
    n_max = 2500  # Sufficient upper limit for this problem
    d_min = typemax(Int)

    for j in 2:n_max
        p_j = pentagonal(j)

        for k in 1:j-1
            p_k = pentagonal(k)
            diff = p_j - p_k

            if diff >= d_min
                continue
            end

            sum_p = p_j + p_k

            if is_pentagonal(diff) && is_pentagonal(sum_p)
                d_min = diff
            end
        end
    end

    return d_min
end

function solve()
    return find_minimum_d()
end

end # module
