"""
Project Euler Problem 12: Highly Divisible Triangular Number

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th
triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:
1: 1
3: 1, 3
6: 1, 2, 3, 6
10: 1, 2, 5, 10
15: 1, 3, 5, 15
21: 1, 3, 7, 21
28: 1, 2, 4, 7, 14, 28

We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
"""
module Problem012

"""
    count_divisors(n)

Count the number of divisors of n using an optimized approach by only
checking up to the square root and counting pairs of divisors.
This reduces the complexity from O(n) to O(√n).
"""
function count_divisors(n)
    count = 0
    for i in 1:isqrt(n)
        if n % i == 0
            # If i divides n, both i and n/i are divisors
            if i^2 == n
                count += 1  # Perfect square case
            else
                count += 2  # Count both i and n/i
            end
        end
    end
    return count
end

"""
    find_first_triangle_with_divisors(min_divisors)

Find the first triangle number that has more than min_divisors divisors.

The nth triangle number can be expressed as T(n) = n(n+1)/2.
A useful mathematical property: when n is even, T(n) = (n/2)(n+1), and when n is odd, T(n) = n((n+1)/2)
These pairs of numbers are coprime (share no common factors).
The number of divisors of a product of coprime numbers equals the product of their individual divisor counts
"""
function find_first_triangle_with_divisors(min_divisors)
    n = 1
    
    while true
        if n % 2 == 0
            # n is even, T(n) = (n/2)*(n+1)
            a = n ÷ 2
            b = n + 1
        else
            # n is odd, T(n) = n*((n+1)/2)
            a = n
            b = (n + 1) ÷ 2
        end
        
        num_divisors = count_divisors(a) * count_divisors(b)
        
        if num_divisors > min_divisors
            return n * (n + 1) ÷ 2
        end
        
        n += 1
    end
end

function solve()
    return find_first_triangle_with_divisors(500)
end

end # module
