"""
Project Euler Problem 27: Quadratic Primes

Euler discovered the remarkable quadratic formula: n² + n + 41.
It turns out that the formula will produce 40 primes for the consecutive integer values 0 ≤ n ≤ 39.
However, when n = 40, 40² + 40 + 41 = 40(40 + 1) + 41 is divisible by 41, and certainly when n = 41,
41² + 41 + 41 is clearly divisible by 41.

The incredible formula n² - 79n + 1601 was discovered, which produces 80 primes for the consecutive values
0 ≤ n ≤ 79. The product of the coefficients, -79 and 1601, is -126479.

Considering quadratics of the form:
n² + an + b, where |a| < 1000 and |b| ≤ 1000

Find the product of the coefficients, a and b, for the quadratic expression that produces the maximum
number of primes for consecutive values of n, starting with n = 0.
"""
module Problem027

using ProjectEulerSolutions.Utils.Primes: is_prime

"""
    count_consecutive_primes(a, b)

Count the number of consecutive primes generated by the quadratic expression n² + an + b,
starting from n = 0.
"""
function count_consecutive_primes(a, b)
    n = 0

    while true
        value = n^2 + a*n + b

        if value < 0 || !is_prime(value)
            break
        end

        n += 1
    end

    return n
end

"""
    find_quadratic_with_most_primes()

Find the coefficients a and b for the quadratic expression n² + an + b that produces
the maximum number of primes for consecutive values of n, starting from n = 0.
Returns (a, b, max_count).

For n=0, the formula evaluates to just b, so b must be a prime number for the sequence to start with a prime.
So instead of checking all values of b in the range [-1000, 1000], we only need to check prime values of b in the range [2, 1000].
"""
function find_quadratic_with_most_primes()
    max_count = 0
    max_a = 0
    max_b = 0

    # Generate a list of primes in the range [2, 1000]
    # For n=0, the expression equals b, so b must be prime
    primes_list = [p for p in 2:1000 if is_prime(p)]

    # Iterate through all possible combinations of a and b
    for a in -999:999
        for b in primes_list
            count = count_consecutive_primes(a, b)

            if count > max_count
                max_count = count
                max_a = a
                max_b = b
            end
        end
    end

    return max_a, max_b, max_count
end

function solve()
    a, b, max_count = find_quadratic_with_most_primes()
    @info "Found n² + $(a)n + $b which produces $max_count primes!"
    return a * b
end

end # module
