"""
Project Euler Problem 29: Distinct Powers

Consider all integer combinations of a^b for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

2^2 = 4,  2^3 = 8,   2^4 = 16,  2^5 = 32
3^2 = 9,  3^3 = 27,  3^4 = 81,  3^5 = 243
4^2 = 16, 4^3 = 64,  4^4 = 256, 4^5 = 1024
5^2 = 25, 5^3 = 125, 5^4 = 625, 5^5 = 3125

If they are then placed in numerical order, with any repeats removed, we get the following
sequence of 15 distinct terms: 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024,
3125.

How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤
100?

## Solution approach

We use a brute-force approach with a hash set to track distinct values:
1. Generate all powers a^b for the given ranges
2. Use BigInt to handle arbitrarily large results without overflow
3. Store each computed power in a Set to automatically handle duplicates
4. Return the size of the set

While more sophisticated mathematical approaches exist (analyzing when (a₁)^b₁ = (a₂)^b₂),
the straightforward approach is sufficient given the constraints.

## Complexity analysis

Time complexity: O(n² × log(a^b_max))
- We compute n² = 99² powers
- Each BigInt exponentiation takes O(log(a^b_max)) time
- For our constraints, a^b_max = 100^100, so log(a^b_max) is manageable

Space complexity: O(n² × log(a^b_max))
- We store up to n² distinct BigInt values
- Each BigInt value requires O(log(a^b_max)) space for its digits
"""
module Problem029

"""
    count_distinct_powers(a_min, a_max, b_min, b_max)

Count the number of distinct terms in the sequence generated by a^b for
a_min ≤ a ≤ a_max and b_min ≤ b ≤ b_max.
"""
function count_distinct_powers(a_min, a_max, b_min, b_max)
    unique_powers = Set{BigInt}()

    for a in a_min:a_max
        for b in b_min:b_max
            power = big(a)^b
            push!(unique_powers, power)
        end
    end

    return length(unique_powers)
end

function solve()
    return count_distinct_powers(2, 100, 2, 100)
end

end # module
