"""
Project Euler Problem 45: Triangular, Pentagonal, and Hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle     T_n = n(n+1)/2      1, 3, 6, 10, 15, ...
Pentagonal   P_n = n(3n-1)/2     1, 5, 12, 22, 35, ...
Hexagonal    H_n = n(2n-1)       1, 6, 15, 28, 45, ...

It can be verified that T_285 = P_165 = H_143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

## Solution approach

Key insight: Every hexagonal number is also a triangle number.
Specifically, H_n = n(2n-1) = T_{2n-1} (the (2n-1)th triangle number).

Therefore, we only need to find hexagonal numbers that are also pentagonal.
Start from H_144 and check each hexagonal number for pentagonality using
the inverse formula.

## Complexity analysis

Time complexity: O(k)
- k iterations until finding the next tri-pent-hex number
- Each pentagonal check takes O(1) time

Space complexity: O(1)
- Only store current hexagonal index and computed values

## Mathematical background

Hexagonal numbers H_n = n(2n-1) are always triangular:
H_n = n(2n-1) = T_{2n-1} where T_m = m(m+1)/2
For m = 2n-1: T_{2n-1} = (2n-1)(2n)/2 = n(2n-1) = H_n
"""
module Problem0045

using ProjectEulerSolutions.Utils.Sequences: hexagonal_number, is_pentagonal

"""
    find_next_tri_pent_hex()

Find the next number after 40755 that is triangle, pentagonal, and hexagonal.
Since all hexagonal numbers are also triangle numbers (H_n = T_{2n-1}),
we just need to find the next hexagonal number that is also pentagonal.
"""
function find_next_tri_pent_hex()
    # Start from the next hexagonal number after H_143
    n = 144

    while true
        hex_num = hexagonal_number(n)
        if is_pentagonal(hex_num)
            return hex_num
        end
        n += 1
    end
end

function solve()
    result = find_next_tri_pent_hex()
    @info "Found next triangular-pentagonal-hexagonal number: $result"
    return result
end

end # module
