"""
Project Euler Problem 44: Pentagon Numbers

Pentagonal numbers are generated by the formula, P_n=n(3n-1)/2. The first ten pentagonal
numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8.
However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, P_j and P_k, for which their sum and difference are
pentagonal and D = |P_k - P_j| is minimised; what is the value of D?

## Solution approach

Search for pairs (P_j, P_k) where both P_j + P_k and |P_j - P_k| are pentagonal.
To minimize D, check pairs in order of increasing difference. Use the inverse
formula to efficiently test if a number is pentagonal without generating all
pentagonal numbers.

For a number n to be pentagonal: n = k(3k-1)/2, so k = (1 + √(1 + 24n))/6
must be a positive integer.

## Complexity analysis

Time complexity: O(N²)
- Check O(N²) pairs where N is the search limit
- Each pentagonal check takes O(1) time using inverse formula

Space complexity: O(1)
- Only store current best difference and loop variables
"""
module Problem0044

using ProjectEulerSolutions.Utils.Sequences: pentagonal_number, is_pentagonal


"""
    find_minimum_d()

Find the value of D = |P_k - P_j| where P_j and P_k are pentagonal numbers
whose sum and difference are also pentagonal, and D is minimized.

Uses an efficient search strategy by:

 1. Checking pairs in order of increasing difference
 2. Early-skipping pairs that can't have a smaller difference than already found
"""
function find_minimum_d()
    n_max = 2500  # Sufficient upper limit for this problem
    d_min = typemax(Int)

    for j in 2:n_max
        p_j = pentagonal_number(j)

        for k in 1:(j - 1)
            p_k = pentagonal_number(k)
            diff = p_j - p_k

            if diff >= d_min
                continue
            end

            sum_p = p_j + p_k

            if is_pentagonal(diff) && is_pentagonal(sum_p)
                d_min = diff
            end
        end
    end

    return d_min
end

function solve()
    result = find_minimum_d()
    @info "Found minimum pentagonal difference D = $result"
    return result
end

end # module
