"""
Project Euler Problem 2: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

## Solution approach

Use the `fibonacci_sequence` utility function from Utils.Sequences, which efficiently 
generates all Fibonacci numbers up to a given limit using iterative computation. 
Filter the resulting sequence for even-valued terms and sum them using Julia's 
built-in sum function with a generator expression.

## Complexity analysis

Time complexity: O(log n)
- The Fibonacci sequence grows exponentially, so there are approximately log(n) terms
  up to limit n.

Space complexity: O(log n)
- Storage for the generated Fibonacci sequence up to the limit.
"""
module Problem002

using ProjectEulerSolutions.Utils.Sequences: fibonacci_sequence

function solve()
    fibs = fibonacci_sequence(4_000_000)
    return sum(f for f in fibs if f % 2 == 0)
end

end # module
