"""
Project Euler Problem 2: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

## Solution approach

Use the mathematical insight that every third Fibonacci number is even, and these even
Fibonacci numbers follow the recurrence relation: F(n) = 4F(n-3) + F(n-6).
Starting with the first two even Fibonacci numbers (2 and 8), generate subsequent
even terms directly without computing or checking the parity of intermediate terms.

## Mathematical background

In the Fibonacci sequence, the pattern of even/odd follows: odd, odd, even, odd, odd, even...
This means every third term is even. The even Fibonacci numbers form their own sequence:
2, 8, 34, 144, 610, 2584, ... which follows the recurrence F(n) = 4F(n-3) + F(n-6).

## Complexity analysis

Time complexity: O(log n)
- The Fibonacci sequence grows exponentially, so there are approximately log(n) terms
  up to limit n. Since we only generate even terms, we reduce iterations by ~67%.

Space complexity: O(1)
- Uses constant space, storing only the last two even Fibonacci numbers.
"""
module Problem0002

function sum_even_fibonacci(limit)
    limit < 2 && return 0

    a, b = 2, 8
    sum = a + b

    while (c = 4b + a) ≤ limit
        sum += c
        a, b = b, c
    end

    return sum
end

function solve()
    return sum_even_fibonacci(4_000_000)
end

end # module
