"""
Project Euler Problem 45: Triangular, Pentagonal, and Hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle     T_n = n(n+1)/2      1, 3, 6, 10, 15, ...
Pentagonal   P_n = n(3n-1)/2     1, 5, 12, 22, 35, ...
Hexagonal    H_n = n(2n-1)       1, 6, 15, 28, 45, ...

It can be verified that T_285 = P_165 = H_143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""
module Problem045

"""
    hexagonal(n)

Calculate the nth hexagonal number using the formula H_n = n(2n-1).
"""
function hexagonal(n)
    return n * (2n - 1)
end

"""
    is_pentagonal(m)

Check if a given number m is pentagonal using the quadratic formula.
If (1 + sqrt(1 + 24*m))/6 is an integer, then m is a pentagonal number.
"""
function is_pentagonal(m)
    if m <= 0
        return false
    end

    x = (1 + sqrt(1 + 24 * m)) / 6
    return x == trunc(x)
end

"""
    find_next_tri_pent_hex()

Find the next number after 40755 that is triangle, pentagonal, and hexagonal.
Since all hexagonal numbers are also triangle numbers (H_n = T_{2n-1}),
we just need to find the next hexagonal number that is also pentagonal.
"""
function find_next_tri_pent_hex()
    # Start from the next hexagonal number after H_143
    n = 144

    while true
        hex_num = hexagonal(n)
        if is_pentagonal(hex_num)
            return hex_num
        end
        n += 1
    end
end

function solve()
    return find_next_tri_pent_hex()
end

end # module
