"""
Project Euler Problem 2: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

## Solution approach

Use the `Fibonacci` iterator from Utils.Sequences, which efficiently generates
Fibonacci numbers up to a given limit using the iterator protocol. Sum only the
even-valued terms directly during iteration without storing the entire sequence.

## Complexity analysis

Time complexity: O(log n)
- The Fibonacci sequence grows exponentially, so there are approximately log(n) terms
  up to limit n.

Space complexity: O(1)
- Uses constant space with the iterator, no intermediate storage required.
"""
module Problem0002

using ProjectEulerSolutions.Utils.Sequences: Fibonacci

function sum_even_fibonacci(limit)
    result = 0
    for fib in Fibonacci(limit)
        if fib % 2 == 0
            result += fib
        end
    end
    return result
end

function solve()
    return sum_even_fibonacci(4_000_000)
end

end # module
